// Generated by CoffeeScript 2.6.1
(function() {
  var lingy;

  require('yaml');

  lingy = (function() {
    class lingy {};

    lingy.prototype.version = '0.0.1';

    return lingy;

  }).call(this);

}).call(this);
